name: Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore FiveCore.Test
    - name: Build
      run: dotnet build FiveCore.Test --no-restore
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResult  --no-build --verbosity normal
    - name: Codecov
        uses: codecov/codecov-action@v1
        directory: TestResult
        files: ./coverage.cobertura.xml
